[package]
name = "webdav-handler"

# When releasing to crates.io:
# - Update html_root_url in src/lib.rs
# - Update CHANGELOG.md.
# - Run ./generate-readme
# - Create git tag v0.x.y
version = "0.2.0-alpha.6"

readme = "README.md"
description = "handler for the HTTP and Webdav protocols with filesystem backend"
documentation = "https://docs.rs/webdav-handler"
repository = "https://github.com/miquels/webdav-handler-rs"
homepage = "https://github.com/miquels/webdav-handler-rs"
authors = ["Miquel van Smoorenburg <mike@langeraar.net>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["webdav"]
categories = ["web-programming"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.playground]
features = ["full"]

[lib]
name = "webdav_handler"
path = "src/lib.rs"

[features]
default = []
actix-compat = [ "actix-web" ]
warp-compat = [ "warp", "hyper" ]
all = [ "actix-compat", "warp-compat" ]

[[example]]
name = "actix"
required-features = [ "actix-compat" ]

[[example]]
name = "warp"
required-features = [ "warp-compat" ]

[dependencies]
bytes = "1.0.1"
futures = "0.3.12"
handlebars = "3.5.2"
headers = "0.3.3"
htmlescape = "0.3.1"
http = "0.2.3"
http-body = "0.4.0"
lazy_static = "1.4.0"
libc = "0.2.82"
log = "0.4.13"
lru = "0.6.3"
mime_guess = "2.0.3"
parking_lot = "0.11.1"
percent-encoding = "1.0.1"
pin-project = "1.0.4"
pin-utils = "0.1.0"
regex = "1.4.3"
tokio = { version = "1.0.2", features = [ "rt-multi-thread", "io-util", "net", "time", "sync" ] }
# time = { version = "0.2.24", default-features = false }
time = { version = "0.2.24", features = ["std"] }
url = "2.2.0"
uuid = { version = "0.8.2", features = ["v4"] }
xml-rs = "0.8.3"
xmltree = "0.10.2"

hyper = {version = "0.14.2", optional = true }
warp = { version = "0.3.0", optional = true }
#actix-web = { version = "3.3.2", optional = true }
actix-web = { version = "4.0.0-beta.1", optional = true }

winapi = {version = "0.3.9", features = ["impl-debug", "impl-default"]}

[dev-dependencies]
clap = "2.33.3"
env_logger = "0.8.2"
hyper = { version = "0.14.2", features = [ "http1", "http2", "server", "stream", "runtime" ] }
tokio = { version = "1.0.2", features = ["full"] }

